language: objective-c
os:
- osx
osx_image:
- xcode12.5

addons:
  homebrew:
    packages:
      - git-lfs
      - doxygen
      - dylibbundler
    update: true
install:
  - chmod +x ./scripts/install_macos.sh
  - ./scripts/install_macos.sh

script:
  - ruby -v
